#!/usr/bin/env sh
DIR="${DIR:-$BLOCK_INSTANCE}"
DIR="${DIR:-$HOME}"
ALERT_LOW="${ALERT_LOW:-$1}"
ALERT_LOW="${ALERT_LOW:-10}" # color will turn red under this value (default: 10%)

LOCAL_FLAG="-l"
if [ "$1" = "-n" ] || [ "$2" = "-n" ]; then
    LOCAL_FLAG=""
fi

if [ "${LABEL}" -ne "1" ]; then
  df -h -P $LOCAL_FLAG "$DIR" | awk -v alert_low=$ALERT_LOW '
  /\/.*/ {
          # full text
          print label $4

          # short text
          print label $4

          use=$5

          # no need to continue parsing
          exit 0
  }

  END {
          gsub(/%$/,"",use)
          if (100 - use < alert_low) {
                  # color
                  print "#FF0000"
          } else {
            print "#FFFFFF"
          }
  }
  '
else
  echo "hd"
  echo ""
  echo $LABEL_COLOR
fi

if [ "${BLOCK_BUTTON}" -eq "1" ]; then
  i3-msg exec "kitty --session $HOME/.config/i3/disk-kitty.startup"
fi