#!/usr/bin/env sh
TYPE="${BLOCK_INSTANCE:-mem}"

if [ "${LABEL}" -ne "1" ]; then
        awk -v type=$TYPE '
        /^MemTotal:/ {
                mem_total=$2
        }
        /^MemFree:/ {
                mem_free=$2
        }
        /^Buffers:/ {
                mem_free+=$2
        }
        /^Cached:/ {
                mem_free+=$2
        }
        END {
                free=mem_free/1024/1024
                used=(mem_total-mem_free)/1024/1024
                total=mem_total/1024/1024
                pct=0
                if (total > 0) {
                        pct=used/total*100
                }

                # full text
                printf("%.1fG/%.1fG (%.f%%)\n", used, total, pct)

                # short text
                printf("%.f%%\n", pct)

                # color
                if (pct > 90) {
                        print("#FF0000")
                } else if (pct > 80) {
                        print("#FFAE00")
                } else if (pct > 70) {
                        print("#FFF600")
                } else {
                        print("#FFFFFF")
                }
        }
        ' /proc/meminfo
else
  echo "mem"
  echo
  echo $LABEL_COLOR
fi

if [ "${BLOCK_BUTTON}" -eq "1" ]; then
  i3-msg exec "kitty --session $HOME/.config/i3/memory-kitty.startup"
fi
