#!/usr/bin/env bash

if [ "${LABEL}" -ne "1" ]; then
  IP_ADDRESS=$(ifconfig "$1" | awk '/inet [0-9]{0,3}\.[0-9]{0,3}\.[0-9]{0,3}\.[0-9]{0,3}/ {print $2}')

  echo $IP_ADDRESS
  echo $IP_ADDRESS
  echo "#FFFFFF"
else
  echo net
  echo
  echo $LABEL_COLOR
fi


if [ "${BLOCK_BUTTON}" -eq "1" ]; then
  i3-msg exec "kitty --session $HOME/.config/i3/nmtui-kitty.startup"
fi
