#!/usr/bin/env bash

git clone --separate-git-dir=$HOME/.dotfiles https://github.com/steelsojka/dotfiles2.git $HOME/.dotfiles-tmp
rsync -avzP --exclude=".git" $HOME/.dotfiles-tmp/.??* $HOME
rsync -avzP $HOME/.dotfiles-tmp/. $HOME
rm -r $HOME/.dotfiles-tmp

# Install nix
sh <(curl -L https://nixos.org/nix/install) --no-daemon

# Install nnn plugins
sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)"
