#!/usr/bin/env sh

if [ "${LABEL}" -ne "1" ]; then
  $HOME/.config/i3blocks/scripts/cpu/cpu_usage
else
  echo cpu
  echo cpu
  echo $LABEL_COLOR
fi


if [ "$BLOCK_BUTTON" -eq "1" ]; then
  i3-msg exec "kitty --session $HOME/.config/i3/cpu-kitty.startup"
fi
